### ISSUE TITLE
Problem with some aicraft in Linux

### ISSUE THREAD

**Issue by suplere** [vranki/ExtPlane#10]
Hello,

I have problem with this plugin in Ubuntu 13.04 64b. Where I have plugin in /Resources/plugins and I choose some of the default aicraft I get this error:
![extplane](https://f.cloud.github.com/assets/5626940/1904156/f8088ef6-7c8b-11e3-8ede-70bed9d992c5.png)
(this screen is error for C 172SP).

I have X-plane 10.25.

With old aircraft works fine (for example PC-12 from CalAir).

**Comment by vranki** [comment]
I just pushed a fix for this. 

Longer explanation for the issue at: http://stackoverflow.com/questions/25661295/why-does-qcoreapplication-call-setlocalelc-all-by-default-on-unix-linux

Thanks for reporting and sorry for long delay before fixing.
