### ISSUE TITLE
Changing just one element of an array dataref?

### ISSUE THREAD

**Issue by wotaskd** [vranki/ExtPlane#11]
First of all, congratulations. This is such an amazing project. It makes building custom cockpits SO much easier! :)

I have a question though. How am I supposed to change the value of just one element of an array dataref? As an example, QPAC A320 uses one single dataref for all light switches"

AirbusFBW/OHPLightSwicthes

The 4th element of the array is the left landing light and the 5th is the right landing light. If I create two buttons and use the set command on each:

set AirbusFBW/OHPLightSwicthes [0,0,0,2]
set AirbusFBW/OHPLightSwicthes [0,0,0,0,2]

That won't work as by sending the second command I'll automatically disable the previous one.

I guess one way would be to subscribe to changes on the dataref and then parsing the data to identify current state of each item and send the info back -- but arrays can get quite large and the process can become quite convoluted. I'd love to be able to have an option like set {dataref} {array_index} {value} instead...

Makes sense?

**Comment by HoBu23** [comment]
@vranki I have tried out your example like this:

set laminar/B738/electric/panel_brightness [,,0.45]

This should set the cabinelight. I have leve blank the first and second element as you have postet. But it doesn't work.
PLEASE HELP. I'm the developer of x-Devices. I will change my software to ExtPlane plugin. But this issue is a big obstacle.

**Comment by HoBu23** [comment]
I would like to test that. Unfortunately I'm not familiar with creating a plugin for MAC OS. I am developing in "java" on mac. Can i get a mac.xpl please to test the future version?

**Comment by HoBu23** [comment]
Ok, thanks for your answer. I will try it.

**Comment by HoBu23** [comment]
I have tested your latest branch:

this one works:
set laminar/B738/electric/panel_brightness [,,1,]
ufa laminar/B738/electric/panel_brightness [3,1,1,0]

but not this:
set laminar/B738/electric/panel_brightness [,,1,]
ufa laminar/B738/electric/panel_brightness [3,1,0,0]

**Comment by vranki** [comment]
Thanks for testing, looks like there is still some issues left. I'll try to get it fixed soon.

**Comment by vranki** [comment]
Thanks @HoBu23 , that was a stupid copy-paste error by me. I'll merge this change as it seems to work now.

**Comment by vranki** [comment]
Fixed in PR #39
