### ISSUE TITLE
Test the extplane 2.0 before merging it to master.

### ISSUE THREAD

**Issue by vranki** [vranki/ExtPlane#16]
There is new major version of ExtPlane waiting for merge in branch staging/version2

I'd like to get feedback and testing results for it before merging to master. I'd like to do it quite soon to avoid merge conflicts with other changes.

**Comment by JanC** [comment]
Hi,
is this ticket still valid? What are the major changes in 2.0? I'm planning to use ExtPlane and if 2.0 is stable enough, I'd use it.
cheers

**Comment by vranki** [comment]
It has been now merged so testing can continue in master.
Major changes are mostly architectural which are not visible for end user and the transformer support. The X-Plane plugin should work as before.
