### ISSUE TITLE
Build server for latest versions? Future release coming soon?

### ISSUE THREAD

**Issue by waynepiekarski** [vranki/ExtPlane#21]
I want to recommend the ExtPlane plugin for a future open-source project I'm working on for Android devices, and I noticed you had some builds linked for v0.1 on the main page.

However, there were some race conditions around data arrays in 0.1 where they would be corrupted, which are fixed in the latest master. Do you maintain a build server anywhere with plugins compiled for win/mac/linux for the latest versions that I can refer people to download? (I can build it on MinGW for myself but would rather link to a common tested version) 

Thanks for putting ExtPlane together, it is perfect to support my Android app, and the latest master seems to work great.

**Comment by vranki** [comment]
Hi,
Currently there is no official build server and builds are made by developers. That sucks, 
and I've been working on mxe build to cross-compile windows binaries on Linux. 
It works, but has not been tested properly (required dll's etc). This script is in
scripts/cross-compile-win64-from-lin.sh

This would enable making a build server that would automatically build win & lin binaries
from git. I have no clue if mac binaries could be build like this.

If you want to help, you could test the cross compilation script and figure out if any dll's or anything else needs to be shipped with the windows plugin.

**Comment by waynepiekarski** [comment]
I don't know much about cross-compilation and have never used X-Plane on Mac or Linux. For now, I've managed to compile a plugin on Windows for my own purposes. I link to my own binaries, but when you are ready to do a new release of ExtPlane v2 or later, I will refer to your binaries.

My new project I just released is an Android CDU for the Zibo 737, open source under GPLv3:
https://play.google.com/store/apps/details?id=net.waynepiekarski.xplanecdu&hl=en
https://github.com/waynepiekarski/XPlaneCDU

**Comment by vranki** [comment]
Hi,
I added XPlaneCDU to list of known users in Readme. Btw there is a typo on Google play description, it says ExtPanel instead of ExtPlane. 
My work on automated cross-compilation continues. Linux binaries are already available in GitHub releases.

**Comment by waynepiekarski** [comment]
Thanks for adding my project to your list. I have fixed up the Google Play description, thanks!

**Comment by waynepiekarski** [comment]
It looks like you have builds appearing now at https://github.com/vranki/ExtPlane/releases/ ... are these builds good to distribute to users? Is there a static link to the latest ZIP file that always remains the same?

**Comment by vranki** [comment]
The untagged releases are automatically built from git's master branch so they can be considered "experimental, but should work". I'll tag known good releases with a version tag. Probably the current version could be considered as one.
