### ISSUE TITLE
handling of strings

### ISSUE THREAD

**Issue by sum1els** [vranki/ExtPlane#24]
hi, i would it be possible to implement the handling/parsing of strings ? it comes back as a type DATA and i can do a decode back to the string, but would be nice to subscribe to a string dataref and get the string back. thank you !

**Comment by vranki** [comment]
Yep, string could be handled as a special data dataref. Can be done.

**Comment by vranki** [comment]
I just pushed a new version with support on modifiers. See the updated readme on how to get data datarefs as string.

**Comment by sum1els** [comment]
Awesome thank you  !!!
