### ISSUE TITLE
xplane crashes on shutdown when client is still connected

### ISSUE THREAD

**Issue by sum1els** [vranki/ExtPlane#28]
As subject suggests, with a client still connected, when you close xplane (at least on my machine), XPlane crashes on exit. When the client disconnects first, xplane exits cleanly.

Is it a known issue ?

**Comment by vranki** [comment]
Nope, thanks for reporting. Should be easy to reproduce and hopefully to fix.

**Comment by sum1els** [comment]
it doesn't seem to happen anymore, so don't worry about it. Thanks !
