### ISSUE TITLE
No initial value when second client subs (with accuracy set)

### ISSUE THREAD

**Issue by sum1els** [vranki/ExtPlane#30]
Hi,

I have a client and on some datarefs I supply an accuracy value to hopefully keep the updates to a minimum, however, when I subscribe from two different clients with no accuracy, both clients get the update (and the second client also gets the initial value), but, when I do the same with an accuracy value set, the second client never gets an initial value, only when the value changes ? Is there something that can be done, or should I remove all the accuracy settings from my subs ?

Thanks!!

no accuracy:
-------------
client 1: subs with no accuracy:

sub sim/weapons/weapon_count
ui sim/weapons/weapon_count 24
ui sim/weapons/weapon_count 24 <<< update from second client sub

client 2: subs with no accuracy:
sub sim/weapons/weapon_count
ui sim/weapons/weapon_count 24 <<< initial value received

with accuracy:
--------------

client 1: subs with accuracy:

sub sim/weapons/weapon_count 1
ui sim/weapons/weapon_count 24
				                         <<< no update when second client sub

client 2: subs also with accuracy:

sub sim/weapons/weapon_count 1
				                         <<< no initial value received

**Comment by vranki** [comment]
Could you test with code found in branch bugfix/no_initial_value_on_second_sub

That should fix the issue.

**Comment by sum1els** [comment]
gonna test it today, thanks Ville

**Comment by sum1els** [comment]
looks good so far, when second client subscribes to a dref, the first client does not get an update (which is fine), but at least the second client subscribing (with accuracy set) receives an initial value now ... thanks Ville !

**Comment by vranki** [comment]
Merged to master, closing this issue.
