### ISSUE TITLE
ExtPlane Plugin re: XP9.7

### ISSUE THREAD

**Issue by ssharpe83713** [vranki/ExtPlane#33]
I downloaded the ExtPlane plugin, unzipped it, and placed it in my XP9.7 Resources/plugins/ folder.  When I launch XP, ExtPlane does not appear in the list of plugins to enable/disable (like AutoGate and XSquawkBox).  I'm using Mac OS X High Sierra.  Any ideas??

**Comment by ssharpe83713** [comment]
Yeah...XP9.7....I know it's old, but it works for me (and I don't have to
upgrade my hardware for the increased specs of the newer versions)!

I just expected that it would appear on the Plugins Admin page to confirm
proper installation as other plugins do.  I also thought it would prompt me
to enter an IP address.  When I launch ExtPlane-Panel.app (to test it), the
app brings up a black window with a line that reads, "Connection refused:
127.0.0.1:0:

Steve

**Comment by ssharpe83713** [comment]
Yeah...XP9.7....I know it's old, but it works for me (and I don't have to upgrade my hardware for the increased specs of the newer versions)!

I just expected that it would appear on the Plugins Admin page to confirm proper installation as other plugins do.  I also thought it would prompt me to enter an IP address.  When I launch ExtPlane-Panel.app (to test it), the app brings up a black window with a line that reads, "Connection refused: 127.0.0.1:0"

**Comment by sum1els** [comment]
i'v never used ExtPlane-Panel, so not sure how that is configured, but read through the Test Session section [here](https://github.com/vranki/ExtPlane#test-session) to check if the ExtPlane plugin is working or look in your XPlane log file.

**Comment by sum1els** [comment]
ExtPlane plugin listens on tcp port 51000, so you might have to put that in somewhere in ExtPlane-Panel to successfully connect to the ExtPlane plugin

**Comment by ssharpe83713** [comment]
Here's the XP9.7 log.txt excerpt:

dlerror:dlopen(/Users/stephensharpe/Documents/X-Plane 9/Resources/plugins/ExtPlane/mac.xpl, 9): no suitable image found.  Did find:
	/Users/stephensharpe/Documents/X-Plane 9/Resources/plugins/ExtPlane/mac.xpl: mach-o, but wrong architecture
	/Users/stephensharpe/Documents/X-Plane 9/Resources/plugins/ExtPlane/mac.xpl: stat() failed with errno=20

**Comment by ssharpe83713** [comment]
It's a 64-bit Mac Mini.  I downloaded (and installed) the plugin from your link above, but there is no change to the log.txt error...

**Comment by sum1els** [comment]
but maybe XP9.7 is 32-bit ?

**Comment by sum1els** [comment]
yeah seems 64-bit was only introduced in XP10+, so 9.7 will still be 32-bit. only option is to try and compile a 32-bit version if you can.

**Comment by ssharpe83713** [comment]
Thanks, so much, for taking the time to work with me on this issue.  I'll take a look at my options!

**Comment by ssharpe83713** [comment]
Since I'm new to compiling with Qt (and my goal is to compile an OS X 32-bit plug-in), how do I let qmake know to compile a 32-bit version....or is it included as part of the overall compile operation??

**Comment by sum1els** [comment]
you would need to build a 32-bit version of Qt first before you can use it with a 32-bit compiler. it might be easier to just get 64bit version of X-Plane ... hahaha

**Comment by vranki** [comment]
Actually building Qt isn't necessary.. The plugin seems to work fine as built with the SDK. But looks like you'll need to compile the plugin yourself for your environment. The plugin itself should work with XP9 AFAIK.
