### ISSUE TITLE
Panels with QSettings

### ISSUE THREAD

**Issue by dankrusi** [vranki/ExtPlane#4]
I've finally gotten around to implementing multiple panels per profile and switching between them. It works well, but breaks the saving model because QSettings syncs automatically (thus when you write any changes when switching a panel it will save your profile). Furthermore, traversing the groups can cause a lot of headaches (for example, copying a panel). How should we solve this? Here are some possible solutions:

Move to XML
Move to JSON (would require Qt5+ I think, not in debian stable)
Extend QSettings to only sync out on command

**Comment by vranki** [comment]
This issue (really old) is related to ExtPlane-Panel. It has had a lot of changes recently so this is probably not even be valid anymore.
