### ISSUE TITLE
undefined symbol: _ZTI15DataRefProvider

### ISSUE THREAD

**Issue by lephisto** [vranki/ExtPlane#43]
Got some Headache getting this up and running with XP11 11.30r2 build 113013 64-bit:

dlerror:/home/mephisto/X-Plane 11/Resources/plugins/extplane/64/lin.xpl: undefined symbol: _ZTI15DataRefProvider

Host OS: Ubuntu Linux 18.04 64bit

What's missing here?

**Comment by vranki** [comment]
Could you check with latest master version if it works now. Thanks for reporting.

**Comment by vranki** [comment]
@lephisto could you confirm that this issue is fixed?

**Comment by lephisto** [comment]
Hello @vranki 

thanks for reply. That one is fixed. Now I seem to suffer from #44 

dlerror:/home/mephisto/X-Plane 11/Resources/plugins/extplane/64/lin.xpl: undefined symbol: _ZN12FloatDataRef16staticMetaObjectE
