### ISSUE TITLE
undefined symbol: _ZN9TcpServerC1EP7QObjectP15DataRefProvider

### ISSUE THREAD

**Issue by lephisto** [vranki/ExtPlane#45]
Building ExtPlane from the latest master 14b351b84bc76de205f8529b24213eff218429a1 produces:

dlerror:/home/mephisto/X-Plane 11/Resources/plugins/extplane/64/lin.xpl: undefined symbol: _ZN9TcpServerC1EP7QObjectP15DataRefProvider

... in the X-Plane 11 logfile.

**Comment by vranki** [comment]
Should now link TcpServer. It's surprisingly difficult to find missing symbols but I found a new linker flag that can be used for it. It warns about X-Plane SDK's symbols also so can't be enabled by default. Any ideas how to automate this are welcome..
