### ISSUE TITLE
Undefined symbol: _ZN9TcpClientC1EP7QObjectP10QTcpSocketP15DataRefProvider

### ISSUE THREAD

**Issue by vdkeybus** [vranki/ExtPlane#47]
X-Plane 11.31
latest ExtPlane (13094c)

**Comment by vdkeybus** [comment]
Looks a lot like #45, but this is now Client instead of Server.

**Comment by vdkeybus** [comment]
This seems to fix it.

diff --git a/extplane-plugin/extplane-plugin.pro b/extplane-plugin/extplane-plugin.pro
index 854f698..3b20aca 100644
--- a/extplane-plugin/extplane-plugin.pro
+++ b/extplane-plugin/extplane-plugin.pro
@@ -105,10 +105,12 @@ QMAKE_POST_LINK += $(MKDIR) $$XPLDIR ; $(COPY_FILE) $(TARGET) $$XPLDIR/$$XPLFILE
 SOURCES += main.cpp \
     xplaneplugin.cpp \
     $$PWD/../extplane-server/tcpserver.cpp \
+    $$PWD/../extplane-server/tcpclient.cpp \
     customdata/navcustomdata.cpp \
     customdata/atccustomdata.cpp
 HEADERS += \
     xplaneplugin.h \
     $$PWD/../extplane-server/tcpserver.h \
+    $$PWD/../extplane-server/tcpclient.h \
     customdata/navcustomdata.h \
     customdata/atccustomdata.h \

**Comment by vranki** [comment]
Could you try with latest master version, should work..

**Comment by vdkeybus** [comment]
Confirming that it works.
