### ISSUE TITLE
Using ExtPlane-Transformer with FlightGear

### ISSUE THREAD

**Issue by mateoconlechuga** [vranki/ExtPlane#50]
Hello, I am trying to start ExtPlane-Transformer, however no output is produced when run from the console? How do I start the application?

**Comment by vranki** [comment]
Which os are you running on? Have you compiled it yourself or using a 
binary?

On Ubuntu, if i run it from console it outputs the following and the window opens:
$ ./extplane-transformer
ExtPlane: void TcpServer::setDataRefProvider(DataRefProvider*) No dataref provider enabled - not listening.

ExtPlane-Transformer is not used very much yet, so there may well be bugs left.

**Comment by mateoconlechuga** [comment]
I am using Windows 10, and just running:

$ extplane-transformer

No window opens or text is output. I can try building it later sometime.

**Comment by vranki** [comment]
Ok, let me know how you succeed. Without any errors it's difficult to debug. Transformer is not used very much yet so there might be hidden bugs.

**Comment by vranki** [comment]
I suppose it works.
