### ISSUE TITLE
Switches with more than 2 positions / Buttons with datarefs

### ISSUE THREAD

**Issue by nbenford** [vranki/ExtPlane#6]
Hi Extplane team,

I'm enjoying this project very much. I'm trying to use Extplane-panel with XHSI and XFMS so as to keep the main monitor an "outside view only" screen. However, some functions still require me to flip back to panel view. The solution is to use a networked copy of Extplane-panel, and populate it with the switches and buttons I need. The only problem is that some switches need to have 3 or more settings, and sometimes a button connected to a dataref would be a better solution, like autopilot buttons. Are such things in the works, or would it be easy for me to change this in my build? My understanding of programming is in the beginning stages, for sure.

**Comment by vranki** [comment]
Looks like this issue is related to ExtPlane-Panel (and possibly fixed in panel). Closing.
