### ISSUE TITLE
Is there a loggnig function within ExtPlane at all?

### ISSUE THREAD

**Issue by mydogspies** [vranki/ExtPlane#63]
Trying to figure out how, or even if, ExtPlane writes a log anywhere? Someone below suggested that it does so into terminal but starting Xplane from terminal does not show any messages from anything and I can't seem to find any way to get Xplane to dump messages into terminal in some kind of verbose mode...

I am not C++ person but if someone can help me out towards how I can make ExtPlane dump a log anywhere, would be super appreciated! :-)

**Comment by vranki** [comment]
Yes, it uses Qt's logging commands that output to standard output. What environment are you running? Do you see X-Plane's output log in the console?

**Comment by vranki** [comment]
Closing. Use Qt's logging. You should see them by running X-Plane from console, at least in Linux.
