### ISSUE TITLE
Crash on get dataref

### ISSUE THREAD

**Issue by btbenedi** [vranki/ExtPlane#66]
I looked through the previous issues and didn't see anything like this.

log.txt file is completely normal on startup, got these:
ExtPlane listening on TCP port 51000 with protocol 1 version 1003
Loaded: Y:\Steam/steamapps/common/X-Plane 11/Resources/plugins/extplane/64/win.xpl (org.vranki.extplaneplugin).

I started up CMD, then "telnet localhost 51000", connects fine, and then I tried "get sim/cockpit/electrical/battery_EQ", returns "ui sim/cockpit/electrical/battery_EQ 1", then I tried "get sim/flightmodel/weight/m_total" and XP crashes.

Nothing in the log after normal startup logging except "--=={This application has crashed!}==--"

**Comment by btbenedi** [comment]
just tried this in PuTTY instead of CMD....and at least the  weight one is working, not sure if that means I have a bad telent version/client or what but would be curious to hear comments

**Comment by vranki** [comment]
Sounds weird. If you are a developer, can you catch the crash in debugger and send backtrace here? If the crash doesn't happen anymore, please close the issue.

**Comment by btbenedi** [comment]
The crash does still happen, but currently due to issue #25. I have stopped using ExtPlane for the time being, if I get ambitious one of these days I'll try and run through debugger and see if I can catch it.
