### ISSUE TITLE
doesn't show in plugins and doesn't seem to work

### ISSUE THREAD

**Issue by memer921** [vranki/ExtPlane#70]
I'm trying to get shahada's FMC working with zibo737, however i'm confused on the install process for the plugin, do i just simply drag the entire extplane-master folder to plugins? or do i gotta mess with all the stuff you mention about git or qt5. i am not a coder. that stuff confuses me. 

when i drag the entire folder over, i see it in plugin admin, but nothing on the drop down list and the fmc unit doesn't pick up the zibo.

**Comment by JRHerculano** [comment]
> I'm trying to get shahada's FMC working with zibo737, however i'm confused on the install process for the plugin, do i just simply drag the entire extplane-master folder to plugins? or do i gotta mess with all the stuff you mention about git or qt5. i am not a coder. that stuff confuses me.
> 
> when i drag the entire folder over, i see it in plugin admin, but nothing on the drop down list and the fmc unit doesn't pick up the zibo.

Drag the extplane plugin to your plugins folder (should be C:\X-Plane 11\Resources\plugins\extplane\64). Start X Plane 11 and check the IP X Plane is using. Close X Plane. Setup the plugin ini file with the IP you just saw on X Plane. Open the android app, start x palne, open zibo 737, give power to the aircraft until you see the FMC coming live and then check your android app, at this point FMC should be duplicated.

**Comment by vranki** [comment]
@memer921 did you get it working?

**Comment by memer921** [comment]
@vranki yes I did. But I did so by finding a post where someone uploaded their file of it in an updated version.

**Comment by vranki** [comment]
Ok. Closing this issue. But if you have any improvement suggestions to README file or something, let us know.
